// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(robot) {
    robot.hear(/badger/i, function(res) {
      return res.send("Badgers? BADGERS? WE DON'T NEED NO STINKIN BADGERS");
    });
    return robot.respond(/open the (.*) doors/i, function(res) {
      var doorType;
      doorType = res.match[1];
      if (doorType === "pod bay") {
        return res.reply("I'm afraid I can't let you do that.");
      } else {
        return res.reply("Opening " + doorType + " doors");
      }
    });
  };

}).call(this);
